spring:
  datasource:
    url: jdbc:sqlserver://spring007.database.windows.net:1433;database=springDemo;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: spring007
    password: password@1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191

